TEC-11227 extend existing annotations
ebx/swagger-core pull request #1
Opened 2021-02-11 15:33 UTC by diepjy

- Add path to the operation annotation as it's going to be easier to generate the documentation from explicitly providing this n the annotation rathe than from Vert.x.
- Add rate limits as this is outside the scope of the OpenAPI spec.
- Bump the version to upload to Archiva.

2021-02-11 20:27 UTC, MarcFletcher requested changes

2021-02-11 20:27 UTC, MarcFletcher commented on modules/swagger-annotations/src/main/java/io/swagger/v3/oas/annotations/Operation.java
> +    String path();
Looking at some of the swagger examples they use a [`@Path`](https://docs.oracle.com/javaee/7/api/javax/ws/rs/Path.html) annotation for this:

    @GET
    @Path("/{username}")
    @Operation(summary = "Get user by user name",
            responses = {

Similarly they seem to use the [`@GET`](https://docs.oracle.com/javaee/7/api/javax/ws/rs/GET.html) annotation as well. There's similarly `@POST`, `@HEAD`, `@PUT` etc.

2021-02-11 20:27 UTC, MarcFletcher commented on modules/swagger-annotations/src/main/java/io/swagger/v3/oas/annotations/ratelimits/RateLimit.java
> +public @interface RateLimit {
If we implemented this as our own annotation, i.e. not inside `@Operation` we wouldn't need to deploy a modified swagger artifact at this point. What do you think?

2021-02-11 20:27 UTC, MarcFletcher commented on modules/swagger-annotations/src/main/java/io/swagger/v3/oas/annotations/ratelimits/RateLimit.java
> +  int callLimit() default -1;
```suggestion
  int maxRequestsInInterval() default -1;
```

2021-02-11 20:27 UTC, MarcFletcher commented on modules/swagger-annotations/src/main/java/io/swagger/v3/oas/annotations/ratelimits/RateLimit.java
> +  int intervalLimitSecs() default -1;
```suggestion
  int maxRequestsDurationSecsInInterval() default -1;
```

2021-02-11 20:27 UTC, MarcFletcher commented on modules/swagger-annotations/src/main/java/io/swagger/v3/oas/annotations/ratelimits/RateLimit.java
> +   * The maximum total number of seconds the operation can be processed. The default of -1 means
```suggestion
   * The maximum runtime seconds of all requests in the interval. The default of -1 means
```

2021-02-11 20:27 UTC, MarcFletcher commented on modules/swagger-annotations/src/main/java/io/swagger/v3/oas/annotations/ratelimits/RateLimit.java
> +   * The interval seconds for the entire rate limit on the operation
```suggestion
   * The interval duration in seconds
```

2021-02-12 11:48 UTC, diepjy commented on modules/swagger-annotations/src/main/java/io/swagger/v3/oas/annotations/Operation.java
> +    String path();
Yes, they're using javax so we can also use that annotation - it shouldn't have any consequences to us during runtime I don't think so this should be safe.

2021-02-12 11:58 UTC, diepjy commented on modules/swagger-annotations/src/main/java/io/swagger/v3/oas/annotations/ratelimits/RateLimit.java
> +public @interface RateLimit {
Yes we can move it out of the operation and move this into the CoreAPI.

2021-02-12 12:25 UTC, diepjy commented
@MarcFletcher RE: the description annotation - this only exists in the spec as a description for a parameter in the URL and not part of the schema where objects are defined - https://swagger.io/specification/ (Components Object). 
but if we're going to be building our own compoenent objects from the response classes themselves, then we can add our own annotations for our own description field we don't need them in this project, espeically if we're generating our own documentation anyway.

We can probably close this repo if we're going define the custom annotations ourselves.

2021-02-12 12:26 UTC, diepjy commented on modules/swagger-annotations/src/main/java/io/swagger/v3/oas/annotations/ratelimits/RateLimit.java
> +  int callLimit() default -1;
If we move this to the core API then I'll make the changes in https://github.com/ebx/main/pull/5362

2021-02-12 18:12 UTC, diepjy commented
Closing the PR as it's not required - we'll define our own annotations and attemot to use the existnig ones.

2021-02-12 18:12 UTC, closed without merging